# This is a basic workflow to help you get started with Actions

name: clone workflow

# Controls when the action will run. 
on:
  workflow_dispatch: 
jobs:
  job_one:
    name: Clone
    runs-on: anjali1020.github.io
    steps:
      - name: testing
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone
      
  
