name: deployment workflow

# Controls when the action will run. 
on:
  push:
    branches: [master] 
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd TestRepo
            git pull https://github.com/anjali1020/anjali1020.github.io.git
