name: deployment workflow

# Controls when the action will run. 
on:
  push:
    branches: [master] 
jobs:
  job_one:
    name: Deploy
    runs-on: anjali1020.github.io
    steps:
      - name: testing
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd TestRepo
            git pull
